name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.socker_senha }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.docker_user }}/restoran:latest .
          docker push ${{ secrets.docker_user }}/restoran:latest

      - name: Deploy to Render
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.render_key }}" \
          -d  ${{ secrets.render_id }}\
          -d "clearCache=true" \
          https://api.render.com/v1/services/${{ secrets.render_id }}/deploys
