name: Docker Build, Push, and Deploy to Render

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Faz o checkout do código
    - name: Checkout do código
      uses: actions/checkout@v3

    # Verificar Docker
    - name: Verificar Docker
      run: docker --version

    # Build da imagem Docker
    - name: Build da imagem Docker
      run: |
        docker build -t pratica:latest .

    # Login no Docker Hub
    - name: Login no Docker Hub
      run: |
        echo "${{ secrets.docker_senha }}" | docker login -u "${{ secrets.docker_user }}" --password-stdin

    # Faz o push da imagem Docker para o Docker Hub
    - name: Push da imagem Docker
      run: |
        docker tag pratica:latest evellyn/pratica:latest
        docker push evellyn/pratica:latest

    # Instalar Render CLI
    - name: Instalar Render CLI
      run: |
        curl -fsSL https://render.com/static/cli/install.sh | bash

    # Verificar Render CLI
    - name: Verificar Render CLI
      run: render --version

    # Login no Render usando a chave de API
    - name: Login no Render
      run: |
        render login --api-key ${{ secrets.render_key }}

    # Fazer o deploy no Render
    - name: Deploy no Render
      run: |
        render deploy --service-id ${{ secrets.render_id }}
